// Generated by CoffeeScript 1.6.2
var Info, alke, os;

alke = require('../../package');

os = require('os');

Info = (function() {
  function Info() {}

  Info.prototype.populate = function() {
    return this.info = {
      app: alke.name + ' version ' + alke.version,
      node: process.version,
      os: os.platform() + ' ' + os.release()
    };
  };

  Info.prototype.toJSON = function() {
    return JSON.stringify(this.info);
  };

  return Info;

})();

module.exports = Info;
