// Generated by CoffeeScript 1.6.2
var User, auth, crypto;

crypto = require('crypto');

User = require('../models/user');

auth = module.exports = {
  encrypt: function(str) {
    var sha;

    sha = crypto.createHash('sha256');
    sha.update(str);
    return sha.digest('hex').toString().toLowerCase();
  }
};
