// Generated by CoffeeScript 1.6.2
var extension, folder, fs, path;

fs = require('fs');

path = require('path');

folder = path.resolve('public/templates/pages');

extension = '.html';

exports.render = function(name, res) {
  var file;

  file = name + extension;
  file = path.join(folder, file);
  return fs.readFile(file, function(err, data) {
    if (err) {
      return res.send(500, err);
    } else {
      res.set('Content-Type', 'text/html');
      return res.send(200, data);
    }
  });
};
