// Generated by CoffeeScript 1.6.3
(function() {
  var config, image, path;

  path = require('path');

  config = require('../../config');

  image = module.exports = {
    getProfileImagePath: function(uid) {
      return path.join(config.system.profiles.path, uid.toString()) + '.' + config.system.profiles.format;
    }
  };

}).call(this);
