// Generated by CoffeeScript 1.6.3
(function() {
  var config, image, path;

  path = require('path');

  config = require('../../config');

  image = module.exports = {
    getProfileImageUrl: function(uid) {
      var url;
      url = path.join(config.system.profiles.path, uid) + config.system.profiles.format;
      return url;
    }
  };

}).call(this);
