// Generated by CoffeeScript 1.6.3
(function() {
  var Goal, Group, User, UserInfo;

  User = require('../models/user');

  Group = require('../models/group');

  UserInfo = require('../models/userInfo');

  Goal = require('../models/goal');

  exports.apply = function(cb) {
    return Goal.drop().success(function() {
      return UserInfo.drop().success(function() {
        return User.drop().success(function() {
          return Group.drop().success(function() {
            return cb(null);
          }).error(function(err) {
            return cb(err);
          });
        }).error(function(err) {
          return cb(err);
        });
      }).error(function(err) {
        return cb(err);
      });
    }).error(function(err) {
      return cb(err);
    });
  };

}).call(this);
