// Generated by CoffeeScript 1.6.2
var User;

User = require('../models/user');

exports.apply = function(cb) {
  return User.sync({
    force: true
  }).success(function() {
    return cb(null);
  }).error(function(err) {
    return cb(err);
  });
};
