// Generated by CoffeeScript 1.6.2
var Group, mysql;

Group = require('../models/group');

mysql = require('../infrastructure/db').mysql;

exports.apply = function(cb) {
  return Group.sync({
    force: true
  }).success(function() {
    return cb(null);
  }).error(function(err) {
    return cb(err);
  });
};
