// Generated by CoffeeScript 1.6.3
(function() {
  var Goal, Group, User, UserInfo, mysql;

  User = require('../models/user');

  Group = require('../models/group');

  UserInfo = require('../models/userInfo');

  Goal = require('../models/goal');

  mysql = require('../infrastructure/db').mysql;

  exports.apply = function(cb) {
    return mysql.sync().success(function() {
      return cb(null);
    }).error(function(err) {
      return cb(err);
    });
  };

}).call(this);
