// Generated by CoffeeScript 1.6.3
(function() {
  var fk1, fk2, fk3, mysql;

  mysql = require('../infrastructure/db').mysql;

  fk1 = 'ALTER TABLE goals ADD CONSTRAINT fk_goals_users FOREIGN KEY (user_id) REFERENCES users (id);';

  fk2 = 'ALTER TABLE users ADD CONSTRAINT fk_users_groups FOREIGN KEY (group_id) REFERENCES groups (id);';

  fk3 = 'ALTER TABLE user_infos ADD CONSTRAINT fk_user_infos_users FOREIGN KEY (user_id) REFERENCES users (id);';

  exports.apply = function(cb) {
    return mysql.query(fk1).success(function() {
      return mysql.query(fk2).success(function() {
        return mysql.query(fk3).success(function() {
          return cb(null);
        }).error(function(err) {
          return cb(err);
        });
      }).error(function(err) {
        return cb(err);
      });
    }).error(function(err) {
      return cb(err);
    });
  };

}).call(this);
