// Generated by CoffeeScript 1.6.2
var mysql;

mysql = require('../infrastructure/db').mysql;

exports.apply = function(cb) {
  var query;

  query = 'ALTER TABLE users ADD CONSTRAINT fk_users_groups FOREIGN KEY (group_id) REFERENCES groups (id);';
  return mysql.query(query).success(function() {
    return cb(null);
  }).error(function(err) {
    return cb(err);
  });
};
