// Generated by CoffeeScript 1.6.3
(function() {
  var Group, User, UserInfo, auth, privileges;

  Group = require('../models/group');

  User = require('../models/user');

  UserInfo = require('../models/userInfo');

  auth = require('../helpers/auth');

  privileges = require('../config').system.privileges;

  exports.apply = function(cb) {
    return Group.create({
      name: 'administrators',
      privilege: privileges.admin
    }).success(function(group) {
      return User.create({
        username: 'span',
        email: 'i@thepans.me',
        password: auth.encrypt('123321'),
        group_id: group.id
      }).success(function(user) {
        return UserInfo.create({
          user_id: user.id,
          nickname: user.username
        }).success(function() {
          return cb(null);
        }).error(function(err) {
          return cb(err);
        });
      }).error(function(err) {
        return cb(err);
      });
    }).error(function(err) {
      return cb(err);
    });
  };

}).call(this);
