// Generated by CoffeeScript 1.6.2
var Forum, Section, mysql;

Forum = require('../models/forum');

Section = require('../models/section');

mysql = require('../infrastructure/db').mysql;

exports.apply = function(cb) {
  var query;

  query = 'ALTER TABLE forums ADD CONSTRAINT fk_forums_sections FOREIGN KEY (section_id) REFERENCES sections (id);';
  return Forum.sync({
    force: true
  }).success(function() {
    return Section.sync({
      force: true
    }).success(function() {
      return mysql.query(query).success(function() {
        return cb(null);
      }).error(function(err) {
        return cb(err);
      });
    }).error(function(err) {
      return cb(err);
    });
  }).error(function(err) {
    return cb(err);
  });
};
