// Generated by CoffeeScript 1.6.2
var Group, privileges;

Group = require('../models/group');

privileges = require('../config').system.privileges;

exports.apply = function(cb) {
  return Group.create({
    name: 'users',
    privilege: privileges.user
  }).success(function(group) {
    return cb(null);
  }).error(function(err) {
    return cb(err);
  });
};
