// Generated by CoffeeScript 1.6.2
var Group, User, auth, privileges;

Group = require('../models/group');

User = require('../models/user');

auth = require('../helpers/auth');

privileges = require('../config').system.privileges;

exports.apply = function(cb) {
  return Group.create({
    name: 'administrators',
    privilege: privileges.admin
  }).success(function(group) {
    return User.create({
      username: 'span',
      email: 'i@thepans.me',
      password: auth.encrypt('123321'),
      group_id: group.id
    }).success(function() {
      return cb(null);
    }).error(function(err) {
      return cb(err);
    });
  }).error(function(err) {
    return cb(err);
  });
};
