// Generated by CoffeeScript 1.6.3
(function() {
  var Group, privileges;

  Group = require('../models/group');

  privileges = require('../config').system.privileges;

  exports.apply = function(cb) {
    return Group.create({
      name: 'users',
      privilege: privileges.user
    }).success(function() {
      return cb(null);
    }).error(function(err) {
      return cb(err);
    });
  };

}).call(this);
