// Generated by CoffeeScript 1.7.1
(function() {
  var app, config, express, http, path, starter;

  express = require('express');

  http = require('http');

  path = require('path');

  config = require('./config');

  starter = require('./starter');

  app = express();

  app.configure(function() {
    app.set('port', config.server.port);
    app.set('views', __dirname + '/views');
    app.use(express.favicon());
    app.use(express.logger('dev'));
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(express.cookieParser(config.server.secret));
    app.use(app.router);
    return app.use(express["static"](path.join(__dirname, 'public')));
  });

  app.configure('development', function() {
    return app.use(express.errorHandler());
  });

  starter.start(app, function(err) {
    var port;
    if (err) {
      console.log('Something is wrong, failed to start application');
      throw err;
    } else {
      port = app.get('port');
      return http.createServer(app).listen(port, function() {
        return console.log('Server listening on port ' + port);
      });
    }
  });

}).call(this);
