// Generated by CoffeeScript 1.6.3
(function() {
  var renderer;

  renderer = require('./helpers/renderer');

  exports.bind = function(app) {
    return app.get('/', function(req, res) {
      return renderer.render('app', res);
    });
  };

}).call(this);
