// Generated by CoffeeScript 1.6.2
var renderer;

renderer = require('./helpers/renderer');

exports.bind = function(app) {
  app.get('/', function(req, res) {
    return renderer.render('home', res);
  });
  app.get('/account', function(req, res) {
    return renderer.render('account', res);
  });
  return app.get('/admin', function(req, res) {
    return renderer.render('admin', res);
  });
};
