// Generated by CoffeeScript 1.7.1
(function() {
  var apiFolder, connector, fs, page, path;

  path = require('path');

  fs = require('fs');

  apiFolder = path.resolve('apis');

  connector = require('./repos/connector');

  page = path.resolve('public/templates/pages/app.html');

  exports.start = function(app, cb) {
    var api, files, repos, _i, _len;
    files = fs.readdirSync(apiFolder);
    for (_i = 0, _len = files.length; _i < _len; _i++) {
      api = files[_i];
      if (path.extname(api) === '.js') {
        (require(path.join(apiFolder, api))).bind(app);
      }
    }
    app.get('/', function(req, res) {
      return fs.readFile(page, function(err, data) {
        if (err) {
          return res.send(500, err);
        } else {
          res.set('Content-Type', 'text/html');
          return res.send(200, data);
        }
      });
    });
    repos = connector.getRepos();
    return repos.initialize(function(err) {
      return cb(err);
    });
  };

}).call(this);
