// Generated by CoffeeScript 1.7.1
(function() {
  var User, should, user, validator;

  should = require('should');

  validator = require('../../models/validator');

  User = require('../../models/user');

  user = new User();

  describe('validator', function() {
    return describe('validate', function() {
      return describe('User', function() {
        beforeEach(function(done) {
          user.id = 1;
          user.username = 'user';
          user.password = 'adkjbicuieeatkldsa';
          user.email = 'test@mygoals.me';
          return done();
        });
        it('should return with err if missing id', function(done) {
          user.id = null;
          return validator.validate(user, function(errs) {
            should.exist(errs);
            return done();
          });
        });
        it('should return with err if username is invalid', function(done) {
          user.username = '&&^';
          return validator.validate(user, function(errs) {
            should.exist(errs);
            return done();
          });
        });
        it('should return with err if username is too long', function(done) {
          user.username = '000000000000000000000000000000000';
          return validator.validate(user, function(errs) {
            should.exist(errs);
            return done();
          });
        });
        return it('should return null if user is valid', function(done) {
          return validator.validate(user, function(errs) {
            should.not.exist(errs);
            return done();
          });
        });
      });
    });
  });

}).call(this);
