// Generated by CoffeeScript 1.7.1
(function() {
  var connector, db;

  db = require('../config').db[0];

  connector = module.exports = {
    getRepos: function() {
      var repos;
      repos = require('./' + db.type + '/repos');
      return repos;
    }
  };

}).call(this);
