// Generated by CoffeeScript 1.6.2
var Forum, Section, forumRepo;

Section = require('../models/section');

Forum = require('../models/forum');

forumRepo = {
  getSection: function(query, cb) {
    return Section.find({
      where: query
    }).success(function(section) {
      return cb(null, section);
    }).error(function(err) {
      return cb(err);
    });
  },
  createSection: function(section, cb) {
    return Section.create(section).success(function(section) {
      return cb(null, section);
    }).error(function(err) {
      return cb(err);
    });
  },
  updateSection: function(section, cb) {
    return Section.find({
      where: {
        id: section.id
      }
    }).success(function(match) {
      var err;

      if (match == null) {
        err = new Error('There is no match to update');
        return cb(err);
      }
      return match.updateAttributes(section).success(function() {
        return cb(null, match);
      }).error(function(err) {
        return cb(err);
      });
    }).error(function(err) {
      return cb(err);
    });
  },
  deleteSectionById: function(id, cb) {
    return Section.find({
      where: {
        id: id
      }
    }).success(function(section) {
      var err;

      if (section == null) {
        err = new Error('There is no match to delete');
        return cb(err);
      }
      return section.destroy().success(function() {
        return cb(null);
      }).error(function(err) {
        return cb(err);
      });
    }).error(function(err) {
      return cb(err);
    });
  },
  getSections: function(query, cb) {
    return Section.findAll({
      where: query
    }).success(function(sections) {
      return cb(null, sections);
    }).error(function(err) {
      return cb(err);
    });
  }
};

module.exports = forumRepo;
