// Generated by CoffeeScript 1.7.1
if (Meteor.isClient) {
  Template.hello.greeting = function() {
    return 'Welcome to app.';
  };
  Template.hello.events({
    'click input': function() {
      if (typeof console !== 'undefined') {
        return console.log('You pressed the button');
      }
    }
  });
}

if (Meteor.isServer) {
  Meteor.startup(function() {});
}
