// Generated by CoffeeScript 1.6.3
var crypto, encrypt, me;

crypto = require('crypto');

me = require('mongo-ember');

encrypt = function(input) {
  var sha;
  sha = crypto.createHash('sha256');
  sha.update(input);
  return sha.digest('hex').toString();
};

exports.init = function() {
  var addAdmin, addSchool, addUser;
  addAdmin = function() {
    var model, user;
    user = {
      username: 'span',
      password: encrypt('psy123321'),
      email: 'span@easyace.ca',
      power: 999
    };
    model = me.getModel('User');
    return model.findOne({
      username: 'span'
    }, function(err, result) {
      if (err) {
        return console.log(err);
      } else if (result == null) {
        user = new model(user);
        return user.save(function(err, result) {
          if (err) {
            return console.log(err);
          } else {
            return console.log('admin span created');
          }
        });
      }
    });
  };
  addUser = function() {
    var model, user;
    user = {
      username: 'user',
      password: encrypt('us123321'),
      email: 'user@easyace.ca'
    };
    model = me.getModel('User');
    return model.findOne({
      username: 'user'
    }, function(err, result) {
      if (err) {
        return console.log(err);
      } else if (result == null) {
        user = new model(user);
        return user.save(function(err, result) {
          if (err) {
            return console.log(err);
          } else {
            return console.log('user user created');
          }
        });
      }
    });
  };
  addSchool = function() {
    var model, school;
    school = {
      name: 'University of Waterloo'
    };
    model = me.getModel('School');
    return model.findOne({
      name: 'University of Waterloo'
    }, function(err, result) {
      if (err) {
        return console.log(err);
      } else if (result == null) {
        school = new model(school);
        return school.save(function(err, result) {
          if (err) {
            return console.log(err);
          } else {
            return console.log('school UW created');
          }
        });
      }
    });
  };
  addAdmin();
  addUser();
  return addSchool();
};
