// Generated by CoffeeScript 1.7.1
exports.init = function(pe) {
  return pe.createModel('User', {
    username: {
      type: String,
      required: true
    },
    password: {
      type: String,
      required: true
    }
  });
};
