// Generated by CoffeeScript 1.8.0
var authorizer;

authorizer = module.exports = {
  canAccessQuestion: function(user, question) {
    var privilege, _i, _len, _ref;
    if (user.power >= 999) {
      return true;
    }
    console.log(JSON.stringify(user));
    console.log(JSON.stringify(question));
    _ref = user.privileges;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      privilege = _ref[_i];
      if ((privilege.school != null) && privilege.school !== question.school) {
        continue;
      }
      if ((privilege.term != null) && privilege.term !== question.term) {
        continue;
      }
      if ((privilege.subject != null) && privilege.subject !== question.subject) {
        continue;
      }
      if ((privilege.course != null) && privilege.course !== question.course) {
        continue;
      }
      return true;
    }
    return false;
  }
};
