// Generated by CoffeeScript 1.7.1
var nm, transporter;

nm = require('nodemailer');

transporter = nm.createTransport({
  service: 'Gmail',
  auth: {
    user: 'span@easyace.ca',
    pass: 'psy123321'
  }
});

exports.sendMail = function(to, subject, content, cb) {
  var options;
  options = {
    from: 'EasyAce',
    to: to,
    subject: subject,
    html: content
  };
  return transporter.sendMail(options, cb);
};
