// Generated by CoffeeScript 1.8.0
var fs, handlebars, path, pdfFolder, pdflatex, spawn, sys, texFolder;

sys = require('sys');

spawn = require('child_process').spawn;

handlebars = require('handlebars');

path = require('path');

fs = require('fs');

pdfFolder = path.resolve('temp/pdfs');

texFolder = path.resolve('temp/texs');

pdflatex = module.exports = {
  compileTest: function(test, template, settings, cb) {
    var obj, tex, texFile;
    obj = {
      test: test,
      settings: settings
    };
    template = handlebars.compile(template);
    tex = template(obj);
    texFile = path.join(texFolder, test._id + '.tex');
    return fs.writeFile(texFile, tex, function(err) {
      var process;
      if (err) {
        return cb(err);
      } else {
        process = spawn('pdflatex', ['-job-name', test._id, '-output-directory', folder, texFile]);
        process.on('exit', function(code) {
          var pdfFile;
          pdfFile = path.join(pdfFolder, 'test._id' + '.pdf');
          return cb(null, pdfFile);
        });
        return process.on('error', function(err) {
          return cb(err);
        });
      }
    });
  }
};
