// Generated by CoffeeScript 1.8.0
var exec, fs, handlebars, path, pdfFolder, pdflatex, templateFolder, testTemplateFile, texFolder;

handlebars = require('handlebars');

path = require('path');

fs = require('fs');

exec = require('child_process').exec;

pdfFolder = path.resolve('temp/pdfs');

texFolder = path.resolve('temp/texs');

templateFolder = path.resolve('templates');

testTemplateFile = path.join(templateFolder, 'test.hbs');

pdflatex = module.exports = {
  compileTest: function(test, settings, cb) {
    var obj, template, tex, texFile;
    obj = {
      test: test,
      settings: settings
    };
    template = fs.readFileSync(testTemplateFile);
    template = handlebars.compile(template.toString());
    tex = template(obj);
    texFile = path.join(texFolder, test._id + '.tex');
    return fs.writeFile(texFile, tex, function(err) {
      var cmd;
      if (err) {
        return cb(err);
      } else {
        cmd = 'pdflatex -jobname ' + test._id.toString() + ' -output-directory ' + pdfFolder + ' ' + texFile;
        console.log(cmd);
        return exec(cmd, function(err, stdout, stderr) {
          var pdfFile;
          if (err) {
            return cb(err);
          } else {
            pdfFile = path.join(pdfFolder, 'test._id' + '.pdf');
            return cb(null, pdfFile);
          }
        });
      }
    });
  }
};
