// Generated by CoffeeScript 1.7.1
exports.info = {
  subjects: [
    {
      name: 'Mathematics',
      code: 'MATH',
      terms: [
        {
          name: 'Fall 2014',
          code: '1149',
          courses: [
            {
              number: '135',
              name: 'Algebra for Honours Mathematics'
            }, {
              number: '136',
              name: 'Linear Algebra 1 (Honours Mathematics)'
            }, {
              number: '137',
              name: 'Calculus 1 for Honours Math'
            }
          ]
        }
      ]
    }, {
      name: 'Actuarial Science',
      code: 'ACTSC',
      terms: [
        {
          name: 'Fall 2014',
          code: '1149',
          courses: [
            {
              number: 231,
              name: 'Mathematics of Finance'
            }
          ]
        }
      ]
    }
  ]
};
