// Generated by CoffeeScript 1.7.1
exports.info = {
  terms: [
    {
      name: 'Fall 2014',
      subjects: [
        {
          name: 'MATH',
          courses: [
            {
              name: 'Algebra for Honours Mathematics',
              number: '135'
            }
          ]
        }
      ]
    }
  ]
};
