// Generated by CoffeeScript 1.7.1
(function() {
  var repos, should;

  should = require('should');

  repos = require('../../../repos/sqlite3/repos');

  describe('repos/sqlite3/repos', function() {
    return describe('initialize', function() {
      return it('should initialize the sqlite3 database accordingly', function(done) {
        return repos.initialize(function(err) {
          should.not.exist(err);
          return done();
        });
      });
    });
  });

}).call(this);
