// Generated by CoffeeScript 1.7.1
var config, jwt, me;

me = require('mongo-ember');

jwt = require('jsonwebtoken');

config = require('../config');

exports.bind = function(app) {
  app.post('/api/connect/questions/wechat', function(req, res) {
    var question, user;
    console.log(question.body);
    question = req.body.question;
    user = req.body.user;
    if (user == null) {
      return res.send(401, 'You do not have the permission to access this api');
    }
    return me.authenticate(user, function(err, user) {
      if (err) {
        return res.send(401, 'You do not have the permission to access this api');
      } else {
        console.log(user);
        return res.send(200, user);
      }
    });
  });
  return app.post('/api/connect/auth', function(req, res) {
    var password, user, username;
    username = req.body.username;
    password = req.body.password;
    user = {
      username: username,
      password: password
    };
    return me.authenticate(user, function(err, user) {
      var token;
      if (err) {
        return res.send(401, err.message);
      } else {
        token = jwt.sign(user, config.secret);
        return res.send(200, token);
      }
    });
  });
};
