// Generated by CoffeeScript 1.7.1
var authorizer, config, fs, me, path, pdfFolder;

fs = require('fs');

path = require('path');

me = require('mongo-ember');

authorizer = require('../helpers/authorizer');

config = require('../config');

pdfFolder = path.resolve(config.download.pdfFolder);

exports.bind = function(app) {
  return app.get('/api/download/pdfs/:pid', function(req, res) {
    var pid;
    pid = req.params.pid;
    return fs.readFile(path.join(pdfFolder, pid + '.pdf'), function(err, data) {
      if (err) {
        return res.send(500, err.message);
      } else {
        res.set('Content-Type', 'application/pdf');
        return res.send(data);
      }
    });
  });
};
