// Generated by CoffeeScript 1.7.1
var authorizer, config, fs, path, testsTemplatePath;

fs = require('fs');

path = require('path');

authorizer = require('../helpers/authorizer');

config = require('../config');

testsTemplatePath = path.resolve(config.tests.templatePath);

exports.bind = function(app) {
  return app.get('/api/edit/tests/template', function(req, res) {
    if (!authorizer.isAdmin(req.user)) {
      return res.send(401, 'You do not have the permission to access this');
    }
    return fs.readFile(testsTemplatePath, function(err, data) {
      if (err) {
        return res.send(500, err.message);
      } else {
        return res.send(200, {
          text: data.toString()
        });
      }
    });
  });
};
