// Generated by CoffeeScript 1.7.1
exports.bind = function(app) {
  app.get('api/images/:qid', function(req, res) {});
  app.post('api/images/:qid/:iid', function(req, res) {});
  return app["delete"]('api/images/:qid/:iid', function(req, res) {});
};
