// Generated by CoffeeScript 1.7.1
var config, folder, fs, gm, path;

fs = require('fs');

path = require('path');

gm = require('gm');

config = require('../config');

folder = path.resolve(config.image.questionImageFolder);

console.log(folder);

exports.bind = function(app) {
  app.get('/api/images/questions/:qid', function(req, res) {
    var listFolder, qid;
    qid = req.params.qid;
    listFolder = path.join(folder, qid);
    return fs.readdir(listFolder, function(err, files) {
      var file, list;
      if (err) {
        return res.send(500, err.message);
      } else {
        list = (function() {
          var _i, _len, _results;
          _results = [];
          for (_i = 0, _len = files.length; _i < _len; _i++) {
            file = files[_i];
            if (path.extname(file) === config.image.format) {
              _results.push(file);
            }
          }
          return _results;
        })();
        list.sort(function(a, b) {
          var aTime, bTime;
          aTime = parseInt(a.substr(0, a.length - config.image.format.length));
          bTime = parseInt(b.substr(0, b.length - config.image.format.length));
          return aTime - bTime;
        });
        return res.send(200, list);
      }
    });
  });
  app.post('/api/images/questions/:qid/:iid', function(req, res) {
    var iid, qid;
    qid = req.params.qid;
    return iid = req.params.iid;
  });
  return app["delete"]('/api/images/questions/:qid/:iid', function(req, res) {});
};
