// Generated by CoffeeScript 1.8.0
var authorizer, me;

me = require('mongo-ember');

authorizer = require('../helpers/authorizer');

exports.bind = function(app) {
  return app.get('/api/search/questions/text', function(req, res) {
    var Question, pattern, query, text;
    query = req.query;
    text = query.text;
    Question = me.getModel('Question');
    pattern = new RegExp('.*' + text + '.*', 'ig');
    return Question.find({
      question: pattern
    }, function(err, questions) {
      var ids, question, _i, _len;
      if (err) {
        return res.send(500, err.message);
      } else {
        ids = [];
        for (_i = 0, _len = questions.length; _i < _len; _i++) {
          question = questions[_i];
          ids.push(question._id.toString());
        }
        return res.send(200, ids);
      }
    });
  });
};
