// Generated by CoffeeScript 1.8.0
var authorizer, me;

me = require('mongo-ember');

authorizer = require('../helpers/authorizer');

exports.bind = function(app) {
  return app.get('/api/search/questions/text', function(req, res) {});
};
