// Generated by CoffeeScript 1.6.2
var membership, privileges;

membership = require('../infrastructure/membership');

privileges = require('../config').system.privileges;

exports.bind = function(app) {
  return app.get('/api/admin/info', membership.authorize(privileges.admin, function(req, res) {
    var Info, info;

    Info = require('../models/vm/info');
    info = new Info();
    info.populate();
    return res.send(200, info.toJSON());
  }));
};
