// Generated by CoffeeScript 1.6.2
var membership, privileges, repo;

repo = require('../repos/forumRepo');

privileges = require('../config').system.privileges;

membership = require('../infrastructure/membership');

exports.bind = function(app) {
  app.post('/api/sections', membership.authorize(privileges.admin, function(req, res) {
    return repo.createSection(req.body, function(err, section) {
      if (err != null) {
        return res.send(500, err.message);
      } else {
        return res.send(201, section);
      }
    });
  }));
  app.get('/api/sections', membership.authorize(privileges.admin, function(req, res) {
    return repo.getSections(null, function(err, sections) {
      if (err != null) {
        return res.send(500, err.message);
      } else {
        return res.send(200, sections);
      }
    });
  }));
  app.put('/api/sections/:id', membership.authorize(privileges.admin, function(req, res) {
    return repo.updateSection(req.body, function(err, section) {
      if (err != null) {
        return res.send(500, err.message);
      } else {
        return res.send(200, section);
      }
    });
  }));
  return app["delete"]('/api/sections/:id', membership.authorize(privileges.admin, function(req, res) {
    var id;

    id = req.params.id;
    return repo.deleteSectionById(id, function(err) {
      if (err != null) {
        return res.send(500, err.message);
      } else {
        return res.send(204);
      }
    });
  }));
};
