// Generated by CoffeeScript 1.7.1
(function() {
  exports.bind = function(app) {
    return app.get('/api/users/self', function(req, res) {
      var user_id;
      if (req.user != null) {
        user_id = req.user.id;
        return repo.getUserInfo({
          user_id: user_id
        }, function(err, info) {
          var user;
          if (err != null) {
            return res.send(500, err.message);
          } else {
            user = {
              id: user_id,
              userInfo: info
            };
            return res.send(200, user);
          }
        });
      }
    });
  };

}).call(this);
