// Generated by CoffeeScript 1.7.1
(function() {
  var fs, options, path, repos, sqlite3;

  sqlite3 = require('sqlite3').verbose();

  options = require('../../config').db[0].options;

  path = require('path');

  fs = require('fs');

  repos = module.exports = {
    type: 'sqlite3',
    initialize: function(cb) {
      return fs.readFile(path.join(__dirname, 'initialize.sql'), {
        encoding: 'utf8'
      }, function(err, sql) {
        var db, file;
        if (err) {
          return cb(err);
        } else {
          file = path.join(__dirname, options.file);
          return db = new sqlite3.Database(file, function(err) {
            if (err) {
              return cb(err);
            } else {
              db.serialize(function() {
                return db.exec(sql, function(err) {
                  return cb(err);
                });
              });
              return db.close();
            }
          });
        }
      });
    },
    getRepo: function(name) {
      var repo;
      return repo = require('./' + name + 'Repo');
    }
  };

}).call(this);
