// Generated by CoffeeScript 1.7.1
(function() {
  var User, userRepo;

  User = require('../../models/user');

  userRepo = module.exports = {
    convert: function(row) {
      var user;
      user = new User();
      user.id = row.id;
      user.username = row.username;
      user.password = row.password;
      user.email = row.email;
      return user;
    },
    getUserById: function(id, cb) {
      var sql;
      sql = 'SELECT * FROM users WHERE id = $id';
      return db.get(sql, {
        id: id
      }, function(err, row) {
        var user;
        if (err) {
          return cb(err);
        } else {
          console.log(row);
          user = userRepo.convert(row);
          return cb(err, user);
        }
      });
    },
    getUserByEmailPassword: function(email, password, cb) {
      var sql;
      sql = 'SELECT * FROM users WHERE email = $email AND password = $password';
      return db.get(sql, {
        email: email,
        password: password
      }, function(err, row) {
        var user;
        if (err) {
          return cb(err);
        } else {
          user = userRepo.convert(row);
          return cb(err, user);
        }
      });
    }
  };

}).call(this);
