// Generated by CoffeeScript 1.7.1
var Schema;

Schema = require('mongo-ember').Schema;

module.exports = {
  Error: {
    schema: {
      message: {
        type: String
      },
      type: {
        type: String
      },
      data: {
        type: Schema.Types.Mixed
      }
    },
    auth: {
      c: function(req, error, user, power, cb) {
        return cb(new Error('Creating error from api call is not allowed'));
      },
      ra: function(req, error, user, power, cb) {
        if (power >= 999) {
          return cb(null);
        } else {
          return cb(new Error('You do not have the permission to access this'));
        }
      },
      ro: function(req, error, user, power, cb) {
        if (power >= 999) {
          return cb(null);
        } else {
          return cb(new Error('You do not have the permission to access this'));
        }
      },
      u: function(req, error, user, power, cb) {
        return cb(new Error('Updating error from api call is not allowed'));
      },
      d: function(req, error, user, power, cb) {
        return cb(new Error('Deleting error from api calls is not allowed'));
      }
    }
  }
};
