// Generated by CoffeeScript 1.7.1
module.exports = {
  Question: {
    schema: {
      question: {
        type: String
      },
      hint: {
        type: String
      },
      answer: {
        type: String
      }
    }
  }
};
