// Generated by CoffeeScript 1.6.3
var Schema;

Schema = require('mongo-ember').Schema;

module.exports = {
  Question: {
    schema: {
      question: {
        type: String,
        required: true
      },
      hint: {
        type: String
      },
      answer: {
        type: String
      },
      summary: {
        type: String
      },
      tags: {
        type: [String]
      },
      difficulty: {
        type: Number
      },
      flag: {
        type: Number
      },
      school: {
        type: Schema.Types.ObjectId,
        ref: 'School'
      },
      subject: {
        type: String
      },
      term: {
        type: String
      },
      course: {
        type: String
      }
    },
    validationMessages: {
      question: {
        required: 'Question cannot be empty'
      }
    }
  }
};
