// Generated by CoffeeScript 1.7.1
var Schema;

Schema = require('mongo-ember').Schema;

module.exports = {
  School: {
    schema: {
      name: {
        type: String,
        required: true
      },
      info: {
        type: Schema.Types.Mixed,
        "default": {}
      }
    },
    validationMessages: {
      name: {
        required: 'School name cannot be empty'
      }
    },
    api: {
      c: function(req, res, model, form, cb) {
        var school;
        school = new model(form);
        return school.validate(function(err) {
          if (err) {
            return cb(err);
          } else {
            return model.findOne({
              name: school.name
            }, function(err, result) {
              if (err) {
                return cb(err);
              } else if (result != null) {
                return cb(new Error('School ' + school.name + ' was already in the database'));
              } else {
                return school.save(function(err, result) {
                  if (err) {
                    return cb(err);
                  } else {
                    return cb(null, {
                      code: 201,
                      data: result
                    });
                  }
                });
              }
            });
          }
        });
      }
    },
    auth: {
      c: function(req, user, power, cb) {
        if (power >= 999) {
          return cb(null);
        } else {
          return cb(new Error('You do not have the permission to access this'));
        }
      },
      u: function(req, user, power, cb) {
        if (power >= 999) {
          return cb(null);
        } else {
          return cb(new Error('You do not have the permission to access this'));
        }
      },
      d: function(req, user, power, cb) {
        if (power >= 999) {
          return cb(null);
        } else {
          return cb(new Error('You do not have the permission to access this'));
        }
      }
    }
  }
};
