// Generated by CoffeeScript 1.7.1
(function() {
  var connector, should;

  should = require('should');

  connector = require('../../repos/connector');

  describe('repos/connector', function() {
    return describe('getRepos', function() {
      return it('should return an object which is the correct repos', function(done) {
        var expectedType, repos;
        repos = connector.getRepos();
        expectedType = require('../../config').db[0].type;
        repos.type.should.equal(expectedType);
        return done();
      });
    });
  });

}).call(this);
