// Generated by CoffeeScript 1.6.2
var Post, Sequelize, mysql;

Sequelize = require('sequelize');

mysql = require('../infrastructure/db').mysql;

Post = mysql.define('posts', {
  id: {
    type: Sequelize.INTEGER,
    primaryKey: true,
    unique: true,
    autoIncrement: true,
    allowNull: false
  }
});

module.exports = Post;
