// Generated by CoffeeScript 1.6.3
(function() {
  var Sequelize, User, UserInfo, config, mysql;

  Sequelize = require('sequelize');

  mysql = require('../infrastructure/db').mysql;

  config = require('../config');

  User = require('./user');

  UserInfo = mysql.define('user_infos', {
    user_id: {
      type: Sequelize.INTEGER,
      primaryKey: true,
      unique: true,
      allowNull: false
    },
    nickname: {
      type: Sequelize.STRING,
      unique: true,
      allowNull: false,
      validate: {
        isAlphanumeric: true,
        len: [config.system.username.min, config.system.username.max]
      }
    },
    firstName: {
      type: Sequelize.STRING,
      unique: false,
      allowNull: true
    },
    lastName: {
      type: Sequelize.STRING,
      unique: false,
      allowNull: true
    }
  });

  User.hasOne(UserInfo);

  UserInfo.belongsTo(User);

  module.exports = UserInfo;

}).call(this);
