// Generated by CoffeeScript 1.7.1
(function() {
  var User;

  module.exports = User = (function() {
    function User(id, username, password, email) {
      this.id = id;
      this.username = username;
      this.password = password;
      this.email = email;
    }

    User.prototype.validations = {
      id: {
        required: true
      },
      username: {
        required: true,
        regex: /^([a-zA-Z0-9_]{4,32})$/g
      },
      password: {
        required: true
      },
      email: {
        required: true
      }
    };

    return User;

  })();

}).call(this);
