// Generated by CoffeeScript 1.7.1
(function() {
  var validator;

  validator = module.exports = {
    validate: function(item, cb) {
      var errs, key, regex, required, result, value;
      errs = [];
      for (key in item) {
        value = item[key];
        if (item.hasOwnProperty(key)) {
          required = Object.getPrototypeOf(item).validations[key].required;
          if (value === null && required) {
            errs.push(new Error('Missing required property ' + key));
          }
          regex = Object.getPrototypeOf(item).validations[key].regex;
          if (regex) {
            result = regex.test(value);
            if (!result) {
              errs.push(new Error('Incorrect value for property ' + key));
            }
          }
        }
      }
      if (errs.length === 0) {
        errs = null;
      }
      return cb(errs);
    }
  };

}).call(this);
